---
- name: Test ansible.controller collection
  hosts: all
  gather_facts: false
  become: false
  tasks:
    - ansible.controller.organization:
        name: "Foo"
        state: absent
        controller_host: "192.168.122.249"
        controller_username: admin
        controller_password: redhat
        validate_certs: false
